sudo: false # Migrating from legacy to container-based infrastructure for Travis
            # Ref: http://docs.travis-ci.com/user/migrating-from-legacy/
language: perl
perl:
  - "5.22"
  - "5.20"

before_install:
  - cpanm Test::Kwalitee
  - cpanm Module::Build::Bundle
 